//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int Id_student { get; set; }
        public string Data_lessons { get; set; }
        public int Rating { get; set; }
        public int Id_Disciplina { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Student Student { get; set; }
    }
}
