//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Disciplina = new HashSet<Disciplina>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
        public string Last_name { get; set; }
        public string Biography { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Disciplina> Disciplina { get; set; }
    }
}
